secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
aws:
  s3:
    bucket: <%= ENV['AWS_S3_BUCKET'] %>
    access_key_id: <%= ENV['AWS_S3_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_S3_SECRET_ACCESS_KEY'] %>
twitter:
  consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
facebook:
  app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
